trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
    - script: |
        cd front
        npm run build
      displayName: 'Build Frontend'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'front/dist'
        ArtifactName: 'frontend-dist'

  - job: BuildBackend
    displayName: 'Build Backend'  
    steps:
    - script: |
        cd back
        npm install
        npm test
        npm run build
      displayName: 'Build and Test Backend'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'back'
        ArtifactName: 'backend-dist'
